production:
   auto_create: true
   deny_delete: true
   svn:
     path: /var/opt/alminium/svn
     svnadmin: /usr/bin/svnadmin
     url: http://ホスト名/svn
     hooks: /opt/alminium/hooks/svn
   git:
     path: /var/opt/alminium/git
     git: /usr/bin/git
     options: --bare 
     url: http://ホスト名/git
     hooks: /opt/alminium/hooks/git
   mercurial:
     path: /var/opt/alminium/hg
     hg: /usr/bin/hg
     url: http://ホスト名/hg
     hooks: /opt/alminium/hooks/hg/hgrc
